# Copyright (C) 2023 akquinet GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

POST http://localhost:9020/add-performance-data
Content-Type: application/json

{
  "start": "2022-02-24T10:06:07.413+00",
  "durationInMs": 12,
  "status": "400",
  "message": "{\"Instanz-ID\": 1, \"Useragent\": {\"Produkttypversion\": \"v1\", \"Produktversion\": \"v1.0.2\", \"Auspraegung\": \"Großartig\", \"Plattform\": \"x86\", \"OS\": \"CentOS\", \"OS-Version\": \"21.9.7\", \"client_id\": \"ID_87234234\", \"Matrix-Domain\": \"http://localhost.de\"}, \"Matrix-Domain\": \"http://localhost.de\", \"sizeIn\": 12,\"sizeOut\":144, \"telematikID\": \"112983441234\", \"professionOID\":\"867687\", \"Response\":\"{status: 400}\"}",
  "operation": "RS_LOGIN"
}

###

POST http://localhost:9020/add-statistics-data
Content-Type: application/json

{
  "messengerServices": 12,
  "registeredUsers": 3456,
  "activeUsers": 789
}


### Admin: Nachlieferungen

### queue supplements

POST http://localhost:9021/admin/supplement?from=2023-05-04T12:00:00Z
Authorization: Basic admin secret

### check supplements queue

GET http://localhost:9021/admin/supplement/queue
Authorization: Basic admin secret

### clear remaining supplement queue

DELETE http://localhost:9021/admin/supplement/queue
Authorization: Basic admin secret


### Admin: Bestandsdaten senden

POST http://localhost:9021/admin/send-statistics
Authorization: Basic admin secret

