# Copyright (C) 2023 akquinet GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

spring:
  datasource:
    url: jdbc:postgresql://${RAWDATA_MASTER_DB_HOST}:${RAWDATA_MASTER_DB_PORT}/${RAWDATA_MASTER_DB_NAME}
    password: ${RAWDATA_MASTER_DB_PASSWORD}
    username: ${RAWDATA_MASTER_DB_USER}
    hikari:
      connection-test-query: SELECT 1

  flyway:
    locations: classpath:/db/migration
    clean-on-validation-error: ${RAWDATA_MASTER_CLEAN_ON_ERROR}
    baseline-on-migrate: true # Makes already migrated versions new base on migrate, allowing incremental migration

rawdata-master:
  api:
    port: ${RAWDATA_MASTER_API_PORT}
  admin:
    port: ${RAWDATA_MASTER_ADMIN_PORT}
  rawDataReport:
    url: ${RAWDATA_MASTER_REPORT_URL}
    deliveryRateMinutes: ${RAWDATA_MASTER_REPORT_DELIVERY_RATE_MINUTES}
    autoSupplementOnStart: ${RAWDATA_MASTER_REPORT_AUTO_SUPPLEMENT_ON_START}
  selfDisclosure:
    url: ${RAWDATA_MASTER_SELF_DISCLOSURE_URL}
    deliveryRateMinutes: ${RAWDATA_MASTER_SELF_DISCLOSURE_DELIVERY_RATE_MINUTES}
  statistics:
    url: ${RAWDATA_MASTER_SELF_STATISTICS_URL}
    cron: ${RAWDATA_MASTER_SELF_STATISTICS_CRON}
  cleanup:
    cron: ${RAWDATA_MASTER_SELF_CLEANUP_CRON}
    daysToLive: ${RAWDATA_MASTER_SELF_CLEANUP_DAYS_TO_LIVE}
