version: "3.9"
name: "fachdienst-rawdata-master"

services:
  # depends on database of registration-service
  rawdata_master:
    container_name: rawdata_master
    build:
      context: ./rdm-backend
      args:
        - JAR_FILE=target/rdm-backend-*-standalone.jar
    ports:
      - "9020:9020"
      - "9021:9021"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: local-docker

  upload_mock:
    container_name: upload-mock
    build:
      context: ./rdm-upload-mock
      args:
        - JAR_FILE=target/rdm-upload-mock-*-standalone.jar
    ports:
      - "8191:8191"

  db:
    container_name: rawdata_master_db
    image: postgres:15
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: rawdata-master-db
      POSTGRES_USER: rawdata-master
      POSTGRES_PASSWORD: password
